package Entrega;
// Generated 14-abr-2016 8:24:58 by Hibernate Tools 4.3.1

import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;




/**
 * Recurs generated by hbm2java
 */
@Entity
@Table(name = "recurs")
public class Recurs  implements java.io.Serializable {


     private String nom;
     private Set<Reserva> reservas;
     

    public Recurs() {
    }
      
    public Recurs(String nom) {
        this.nom = nom;
    }
    
    @Id
    
    @Column(name = "nom", unique = true, nullable = false, length = 50)
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "recurs")
    public Set<Reserva> getReservas() {
	return this.reservas;
    }

    public void setReservas(Set<Reserva> reservas) {
	this.reservas = reservas;
    }




}


