package Entrega;
// Generated 14-abr-2016 8:24:58 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Reserva generated by hbm2java
 */
@Entity
@Table(name = "reserva")
public class Reserva  implements java.io.Serializable {


     Date data;
     Integer horainici;
     Integer horafi;
     String comentaris;
     Persona persona;
     Recurs recurs;

    public Reserva() {
    }
     

    public Reserva(Date data, Integer horainici, Integer horafi, String comentaris, Persona persona, Recurs recurs) {
        this.data = data;
        this.horainici = horainici;
        this.horafi = horafi;
        this.comentaris = comentaris;
        this.persona = persona;
        this.recurs = recurs;
    }

    

    @Id
   
    @Column(name = "dataR", unique = true, nullable = false)
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    
    @Id
    
    @Column(name = "horaIni", unique = true, nullable = false)
    public Integer getHorainici() {
        return this.horainici;
    }
    
    public void setHorainici(Integer horainici) {
        this.horainici = horainici;
    }
    
    @Column(name = "horaFi")
    public Integer getHorafi() {
        return this.horafi;
    }
    
    public void setHorafi(Integer horafi) {
        this.horafi = horafi;
    }
    
    @Column(name = "comentaris", length = 255)
    public String getComentaris() {
        return this.comentaris;
    }
    
    public void setComentaris(String comentaris) {
        this.comentaris = comentaris;
    }
    
    @ManyToOne(fetch= FetchType.LAZY)
    @JoinColumn(name="UsernameReserva")
    public Persona getPersona() {
        return persona;
    }

    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    
    @Id
    
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name="RecursReserva")
    public Recurs getRecurs() {
        return recurs;
    }

    public void setRecurs(Recurs recurs) {
        this.recurs = recurs;
    }
    
}


